### ISSUE TITLE
Publish Jekyll site at keywords.nyupress.org

### ISSUE THREAD

**Issue by northgardner** [nyudlts/press-keywords-theme#3]
I will be changing the DNS settings for keywords.nyupress.org tomorrow (Wednesday) at 9am. @mnyrop apologies if you've provided them elsewhere, but could you put any necessary DNS settings (IP address etc) in this ticket?

CC @fauno

**Comment by fauno** [comment]
I see the information for keywords2.hosting.nyu.edu is:

```
keywords2.hosting.nyu.edu.      86400   IN      CNAME   hosting.nyu.edu.
hosting.nyu.edu.                86400   IN      A       159.203.92.10
```

So I think you would have to add the same CNAME. I don't remember if @mnyrop said the server is already configured for the keywords.nyupress.org virtual host, and how/when the TLS certificate is issued.

**Comment by fauno** [comment]
Tomorrow at my 9 AM I'll rebuild the site with the new URL so when you change the DNS everything works.

**Comment by northgardner** [comment]
@fauno Should I switch the DNS at 9:30 then?

**Comment by fauno** [comment]
I'd say whenever the ftp-deploy action is ready, then keywords2.hosting.nyu.edu will have non-working URLs on the home links for a few minutes before you change the DNS.

**Comment by northgardner** [comment]
Which is not a problem, as no one should have the keywords2.hosting.nyu.edu URL. I'll be ready at 9. Just let me know when your done.

**Comment by fauno** [comment]
Sure!  I did these tests, I think everything's ready for the DNS change :)

```bash
# Check if hosting responds to http://keywords.nyupress.org/
curl -vH 'Host: keywords.nyupress.org' http://159.203.92.10/
# It redirects to https://keywords.nyupress.org/ so it looks like it's working

# Check if hosting has a certificate for keywords.nyupress.org
gnutls-cli --sni-hostname=keywords.nyupress.org 159.203.92.10
# Returns the same certificate as the current WP site

**Comment by northgardner** [comment]
OK. I think I need some guidance here @mnyrop. There is only one current  DNS record:

A Keywords 159.203.92.10 

There is no CNAME record for keywords.

Isn't that the IP address for the current WP site? Shouldn't there be a different IP for the new Jekyll site on Web Hosting?
![Screen Shot 2021-08-03 at 4 34 44 PM](https://user-images.githubusercontent.com/13039331/128082461-b8ecee18-4df2-4c3a-8fd0-d9a56f9db821.png)

**Comment by mnyrop** [comment]
@northgardner I checked in with Zach and he said he can try to help. If you send him an email directly he'll be looking out for it.

**Comment by fauno** [comment]
I'll be available tomorrow if you need me

**Comment by northgardner** [comment]
I'm pushing back the launch time, as I await information from Zach. I will try for this afternoon, but will keep this ticket updated.

**Comment by northgardner** [comment]
Success! The new site is live at https://keywords.nyupress.org/. Thanks @mnyrop @coblezc

**Comment by fauno** [comment]
Congrats!!

**Comment by fauno** [comment]
The Keywords Now publication is done but I don't see the changes reflected on the server, could you look at this @mnyrop ?

**Comment by mnyrop** [comment]
@fauno should be updated now!

```sh
➜ curl -X HEAD -i  https://keywords.nyupress.org/
Warning: Setting custom HTTP method to HEAD with -X/--request may not work the
Warning: way you want. Consider using -I/--head instead.
HTTP/2 200
date: Thu, 23 Sep 2021 17:10:46 GMT
server: Apache
last-modified: Thu, 23 Sep 2021 16:55:55 GMT
accept-ranges: bytes
content-length: 19890
content-type: text/html

curl: (18) transfer closed with 19890 bytes remaining to read
```

Looks like the FTP deploy action had a bug that put the `sync-state` file in the server root. I set [this value explicitly](https://github.com/nyu-dss/keywords-data/blob/0177470556575688c3d2c640be24c02e5b34de4c/.github/workflows/ftp-deploy.yml#L34) to put the file in the project directory, so hopefully this should prevent any similar errors in the future.

``` sh 
➜ curl https://keywords.nyupress.org/.ftp-deploy-sync-state.json | head -n 50
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0{
    "description": "DO NOT DELETE THIS FILE. This file is used to keep track of which files have been synced in the most recent deployment. If you delete this file a resync will need to be done (which can take a while) - read more: https://github.com/SamKirkland/FTP-Deploy-Action",
    "version": "1.0.0",
    "generatedTime": 1632410357064,
    "data": [
        {
            "type": "file",
            "name": "README.md",
            "size": 3384,
            "hash": "4744bbd509cb85089c939895d984fc9c6b125e7130aafd5428318bc1b56fe311"
        },
        {
            "type": "folder",
            "name": "about-this-site"
        },
        {
            "type": "folder",
            "name": "african-american-studies"
        },
        {
            "type": "folder",
            "name": "american-cultural-studies"
        },
        {
            "type": "folder",
            "name": "asian-american-studies"
        },
        {
            "type": "folder",
            "name": "assets"
        },
        {
            "type": "folder",
            "name": "author"
        },
        {
            "type": "folder",
            "name": "childrens-literature"
        },
        {
            "type": "folder",
            "name": "comics-studies"
        },
        {
            "type": "folder",
            "name": "critical-race-theory"
        },
        {
            "type": "file",
            "name": "data.json",
  1 4331k    1 50349    0     0   364k      0  0:00:11 --:--:--  0:00:11  364k
```

**Comment by fauno** [comment]
Great, thanks!

**Comment by northgardner** [comment]
Migrated to https://jira.nyu.edu/browse/KEYWORDS-73
