### ISSUE TITLE
Suppressing Keywords Now "books" from homepage and/or menu

### ISSUE THREAD

**Issue by northgardner** [nyudlts/press-keywords-theme#4]
Not sure if this should be here or in /keywords-data, but I'm hoping this is temporary anyway (we'd have one place in Jira for all issues). Could we suppress the Keywords Now sections from appearing on the homepage and/or the Books dropdown menu? How much effort would this take?

**Comment by northgardner** [comment]
Ah, this was just a question at this point! The menu we would remove it from would be the one in the top navigation bar: 
![Screen Shot 2021-09-09 at 4 41 00 PM](https://user-images.githubusercontent.com/13039331/132759642-4f9fa237-2a2f-4e68-8239-c5280861c91c.png)

I probably made some leaps in this description without explaining them, so I'll do it now.

We talked last week about treating the Keywords Now sections as books, so they would each get their own section of the site. Now, that would mean that they would get a place on the homepage:
![Screen Shot 2021-09-09 at 4 49 28 PM](https://user-images.githubusercontent.com/13039331/132760535-e2f29360-8770-4082-a33d-f2d773217bf2.png)

as well as on the Book menu (the menu that appears when you click on "Books" at the top of the site or the down arrow next to it.

The question is: Could we make each Keywords Now section its own book so that it acts like all of the other books on the site, BUT suppress either the listing on the home page OR its appearance in the Books menu, OR both?

(We actually probably want to keep them in the side bar.)

**Comment by fauno** [comment]
Aaah I see. There could be a on/off switch for showing them on the book menu and home page but if they're going to be special pages I'd prefer to create a new post type with their own templates, to avoid having too many conditionals. So this new post type would implement a subset of book features, but won't appear on the menu and the home page.

Unless you actually want to show some of them on menu/homepage in some cases?

And if they don't appear there, how would you find on the site?

**Comment by fauno** [comment]
(Just a reminder that this is a public repository, unlike keywords-data)

**Comment by northgardner** [comment]
OK. And how much effort would creating a new post type take? The editors are putting some pressure on me.

**Comment by fauno** [comment]
I'll work on this tomorrow morning, please let me know if there's
anything else other than looking like a book page and not showing on the
book menu/homepage.

**Comment by northgardner** [comment]
Wait! I don't have the green light from them yet. I just wanted to see how big a task this would be before I tell them when it could be done.

**Comment by fauno** [comment]
Ah, sorry, I expect to do this in no more than 3 hours

**Comment by northgardner** [comment]
OK. I'll ask them what they want. Stay tuned.

**Comment by northgardner** [comment]
OK, they're leaving it up to us. Ultimately, I think it would best to add a second menu to the right of "Book" called "Features" and put these there, but for now I think we can just put the content into the template we have. Further question here: if we add this content to the "Book" template and we want to change them to a different template later on, will that be a problem?

**Comment by fauno** [comment]
I can create a Feature template based on Book so in the future they can differ without conflicts

**Comment by northgardner** [comment]
Great. Or Maybe it should just be a Keywords Now template, so we don't have to think about future cases too much. OK, I'm going to write a new ticket for this.

**Comment by northgardner** [comment]
Migrated to https://jira.nyu.edu/browse/KEYWORDS-74
