### ISSUE TITLE
Tweak stylesheet so that new menu item does not overlap with "Keywords" in top menu bar

### ISSUE THREAD

**Issue by northgardner** [nyudlts/press-keywords-theme#7]
![image](https://user-images.githubusercontent.com/13039331/134567531-96bdb9a9-606a-4351-add9-89e07e1902b8.png)

This is not urgent, but I think we can fix this with a combination of:
1. Less space in between the Home, Books, and Keywords Now menu items
2. Forcing the content of that menu bar onto two lines starting at a wider point (right now it changes to two lines for very small screens, but not a the in-between resolution in the screenshot above

**Comment by fauno** [comment]
Is this something that can be postponed and implemented on the new theme
version or a fix for the current one?

**Comment by northgardner** [comment]
Absolutely. Let's just keep the ticket open. If you want to assign it back to me until then you can.

**Comment by northgardner** [comment]
Migrated to https://jira.nyu.edu/browse/KEYWORDS-75
